### ISSUE TITLE
Request for documentation

### ISSUE THREAD

**Issue by frankbaele** [amoyeh/steer.js#1]
Hi, this is a very interesting and to the point written library but it's really lacking a good api documentation.

The examples and source allow me to reverse engineer some parts but this seems kinda unnecessary.

**Comment by frankbaele** [comment]
ok looked over the documentation link, sorry

**Comment by amoyeh** [comment]
Greetings ~ I am glad that you tested the library , I know there are still many things needs to be done , such as more detail documentation, I am still working on it and will update it when I have time. thanks~

**Comment by frankbaele** [comment]
one remark i have, the current library seems to have a tide coupling between itself and the render engines. 
Any change of just decoupling this entirely and just returning the velocity of of each actor. 

I'm not using pixi or tree.js and having a hard time just getting a velocity back.

**Comment by amoyeh** [comment]
sorry for the late reply, I've been busy for a while. about the tide coupling problem your idea was great about just getting the raw data of positions and so on.  in fact, if you look at the example provided in DemoKart.html (Mario karts running around on track) Line 105 to 130, I used a custom renderer to update every item position from the domain, that might help if you want to implement a custom renderer. and if you need to get the velocity of the unit , you can get it from Unit class, there is a velocity property. or even alter the box2d b2Body physic values. I will also add an example of how to implement or getting raw data of every item as you suggested. please also check on https://www.facebook.com/steerjs. where I update my thoughts and latest info on this library. thanks.
